[package]
name = "windows-ez-overlay"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "*", features = [
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
] }

[profile.release]
lto = true
strip = true
panic = "abort"
codegen-units = 1
